{{- if and .Values.ddiProxy.enabled (not .Values.ddiProxy.tls.secretName) (not .Values.ddiProxy.tls.externalSecret) .Values.ddiProxy.tls.certificate .Values.ddiProxy.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hawkbit.ddiProxy.tlsSecretName" . }}
  labels:
{{ include "hawkbit.labels" . | indent 4 }}
    app.kubernetes.io/component: ddi-proxy
type: kubernetes.io/tls
stringData:
  tls.crt: |
    {{- .Values.ddiProxy.tls.certificate | trim | nindent 4 }}
  tls.key: |
    {{- .Values.ddiProxy.tls.key | trim | nindent 4 }}
{{- end }}
