{{- if and .Values.serviceAccount.create .Values.job.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.job.serviceAccountName }}
  labels:
    {{- include "hawkbit.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.serviceAccount.annotations .Values.serviceAccount.preSync }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.serviceAccount.preSync }}
    "argocd.argoproj.io/hook": PreSync
    "argocd.argoproj.io/sync-wave": "-10"
    {{- end }}
  {{- end }}
{{- end }}
